name: Draft release
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - v**

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

permissions:
  contents: write

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v5
      - name: "Setup: Node"
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: control/package-lock.json
      - name: "Setup: dotnet"
        uses: actions/setup-dotnet@v5
      - name: "Build: dotnet build"
        run: dotnet build
      - name: "Setup: zip"
        shell: bash
        run: |
          if ! command -v zip &> /dev/null
          then
            sudo apt -y update
            sudo apt -y install zip
          fi
      - name: "Configure: Version"
        run: echo "Version=${GITHUB_REF##*/v}" >> $GITHUB_ENV
      - name: "Build: Version the solution"
        run: dotnet msbuild -t:SetVersion -p:NewVersion=${{ env.Version }}
      - name: "Build: dotnet build"
        run: dotnet build
      - name: "Test: dotnet test"
        run: dotnet test --no-build
      - name: "Test: Prepare code coverage"
        run: |
          if test -d ./dist/coverage
          then
            (cd ./dist && zip -r ./coverage.zip ./coverage)
          fi
      - name: "GitHub: Create draft release"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/*.zip
